global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with external systems.
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'python'
    scrape_interval: 1s
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'pushgateway'
    scrape_interval: 1s
    static_configs:
      - targets: ['pushgateway:9091']
      
  - job_name: "fastapi"
    static_configs:
      - targets: ["fastapi:8080"]

rule_files:
  - "alerting_rules.yml"  # Updated to use forward slashes

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]

